language: node_js
node_js:
- 7
- 6
- 5
notifications:
  slack:
    secure: R7AcOD5haHacEt7WTJwKYWYyk6aB5h9wypbKnOEbgPh76yeaf0SDMQWa9QQ55fwg7ZJzi+ntGupCrEYxJaFuui0Q1FEiAcvGPccuMOUF+mfwdGP49+JZzz5P3OAu35rEkF0oW4BnRJt++TMcT8XHKf8rGnNPL7I96S45S493HAecvwPEFdlymquO+AKve1Mx1Ru9ewyYxxtDvd6K1k6QQ5q+RqBr4lG5/IbjVf/aqFTbISn2y/714rijr73GrB7nlIq/OrL2VeSxFWZRqvkq6TZsY5cecw/7YAcFbrbqlKJY0s7tJsBvFIUWwQ7in2DvNyysF7uixXOsOwELmAWAJYXgI0qMqYwVgULjp+3KLnASFmUk93Yzw3esIev8f3iToyab1gpP+Xt1AvLwgV30jSqcG+JNk3PT34gKyNHgRnU0B32HIsLJX8MsPJc49k51xktsIPK/3LgIHtuy9w4OdRNg4aC/chr/qXrbUuxyVkkiv/yqDcUFqWkFNxjSus2i3McQ1B5cZgyonOcjHukgNqeuuEQD3vJ+tdnpTiYF0xarLIgUkF+BN3k1EuGvTOy87pEZOhGgNEkvaEY7PI18MNue8lDRbMR6p4NjGJmXnH6+ii13ezcBFTh5mAwRvDME/sw5UVqpzKEi32HG40bLGq0wYkWb/S1WY5xsY2d4HDU=
